### PR TITLE
LOGTOOL-105 Option to have LoggingToolsProcessor to not use javax.ann…

### PR DESCRIPTION
**Pull request by Sanne**
…otation.Generated

https://issues.jboss.org/browse/LOGTOOL-105

### CODE REVIEW

**Comment by Sanne** [comment]
Please wait a bit more before integrating this, I'm exploring an alternative solution which might not need patching of the AP.

**Comment by Sanne** [comment]
I did indeed find an alternative, described on JIRA LOGTOOL-105

I'm leaving this open so you can decide if you'd like to have this option as well.

**Comment by jamezp** [comment]
Thanks @Sanne. I'll leave it open for now and keep an eye on the jigsaw-dev mailing list.

**Comment by jamezp** [comment]
@Sanne Can you let me know what you think of #60?

**Comment by jamezp** [comment]
Closing this in favor of #60

**Pull request closed without merging**
